# Generated by Django 4.2.1 on 2023-05-29 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
